name: Check Code Quality
on: [push]
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: yarn

      - name: run tests
        run: yarn test

      - name: run lint
        run: yarn lint
