name: Check Code Quality
on: [push]
jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm run test

      - name: run lint
        run: npm run lint
